// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://nodebyte.host/terms",
        "contact": {
            "name": "NodeByte LTD",
            "url": "https://nodebyte.host"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/license/mit"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/metrics": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "View a collection of all host system metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get all system metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MetricsData"
                        }
                    }
                }
            }
        },
        "/api/metrics/cpu": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "View cpu usage and statistics of the host machine",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get cpu information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CPUData"
                        }
                    }
                }
            }
        },
        "/api/metrics/disk": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "View disk usage and statistics of the host machine",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get disk information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DiskData"
                        }
                    }
                }
            }
        },
        "/api/metrics/host": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "View some information about the host machine",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get host information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HostData"
                        }
                    }
                }
            }
        },
        "/api/metrics/memory": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "View memory usage and statistics of the host machine",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get memory information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MemoryData"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "View the health status of the service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthCheckResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CPUData": {
            "type": "object",
            "properties": {
                "current_frequency": {
                    "type": "integer"
                },
                "frequency": {
                    "type": "number"
                },
                "logical_core": {
                    "type": "integer"
                },
                "physical_core": {
                    "type": "integer"
                }
            }
        },
        "api.DiskData": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "free_bytes": {
                    "type": "integer"
                },
                "total_bytes": {
                    "type": "integer"
                },
                "usage_percent": {
                    "type": "number"
                }
            }
        },
        "api.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "metrics": {
                    "$ref": "#/definitions/api.Metrics"
                },
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.HostData": {
            "type": "object",
            "properties": {
                "kernel_version": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "api.MemoryData": {
            "type": "object",
            "properties": {
                "available_bytes": {
                    "type": "integer"
                },
                "total_bytes": {
                    "type": "integer"
                },
                "usage_percent": {
                    "type": "number"
                },
                "used_bytes": {
                    "type": "integer"
                }
            }
        },
        "api.Metrics": {
            "type": "object",
            "properties": {
                "ping": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "api.MetricsData": {
            "type": "object",
            "properties": {
                "cpu": {
                    "$ref": "#/definitions/api.CPUData"
                },
                "disk": {
                    "$ref": "#/definitions/api.DiskData"
                },
                "host": {
                    "$ref": "#/definitions/api.HostData"
                },
                "memory": {
                    "$ref": "#/definitions/api.MemoryData"
                }
            }
        }
    },
    "securityDefinitions": {
        "bearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.2.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "SysCapture API",
	Description:      "OpenAPI documentation for SysCapture API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
